= Quickstart for developers



*Completion time*: *10 minutes*.

TIP: Be sure to first complete one of the Luna Streaming installation options (locally or on a cloud provider) before performing these post-install steps.


In this quickstart for developers, we'll cover:

* Setting up port forwarding to access Pulsar services outside your Kubernetes (K8s) cluster.
* Configuring the Apache Pulsar command line utilties.
* Accessing basic Apache Pulsar functions using the command line utilities.

== Set up port forwarding

In order to access Apache Pulsar outside of the K8s cluster, you'll need to utilize port forwarding unless Ingress is.

Begin by getting a list of your Luna Streaming K8s services and ports:

[source,bash]
----
kubectl get services
----

*Output*:

[source,bash]
----
Update output
----

In the output above, the service of interest is:

* Update this list
 ** *8080/TCP*: GraphQL interface
 ** *8081/TCP*: REST authorization service for generating tokens
 ** *8082/TCP*: REST interface
 ** *9042/TCP*: CQL service

Those are the ports we'll need to forward for CQLSH and Stargate access.

To configure port forwarding:

. Open a new terminal.
. Run the `kubectl port-forward` command in the background:
+
[source,bash]
----
Update this command...

 kubectl port-forward svc/k8ssandra-dc1-stargate-service 8080 8081 8082 9042 &
----
+
*Output*:
+
[source,bash]
----
Update this output...

 [1] 80940

 ~/
 Forwarding from 127.0.0.1:8080 -> 8080
 Forwarding from [::1]:8080 -> 8080
----

=== Terminate port forwarding

To terminate the port forwarding service:

. Get the process ID:
+
[source,bash]
----
 jobs -l
----
+
*Output*:
+
[source,bash]
----
 [1]  + 80940 running    kubectl port-forward svc/k8ssandra-dc1-stargate-service 8080 8081 8082
----

. Kill the process
+
[source,bash]
----
 kill 80940
----
+
*Output*:
+
[source,bash]
----
 [1]  + terminated  kubectl port-forward svc/k8ssandra-dc1-stargate-service 8080 8081 8082
----

TIP: Exiting the terminal instance will terminate the port forwarding service.


[#download-pulsar]
== Download and configure Apache Pulsar command line tools

To interact with your Astra Streaming topic, you can use the command line tools included with the Apache Pulsar distribution.

Download and configure Apache Pulsar:

. Download the current binary of https://pulsar.apache.org/en/download[Apache Pulsar].
. Extract the Apache Pulsar zip file to a convenient directory.
. Copy the `client.conf` file you downloaded in <<Download Pulsar connection information>> and copy it to the `/conf` directory.

The Apache Pulsar command line tools are now configured and ready to use.

[#use-pulsar-tools]
== Use the Apache Pulsar command line tools

You can use the Apache Pulsar command line tools to easily interact with your Astra Streaming Pulsar instance. We'll take a look at the most useful commands in this section.

[NOTE]
====
You can find all of the Apache Pulsar command line utilities in the `/bin` directory within the Pulsar distribution.
====

[#get-instance-info]
=== Get information about your Astra Streaming Pulsar instance

Since you may not remember details about your Astra Streaming Pulsar instance, let's query some information using the `pulsar-admin` utility:

[TIP]
====
If you can't remember your tenant name, retrieve it from the Astra Streaming web console.
====

. Retrieve the namespaces associated with your tenant:
+
[source,bash]
----
./pulsar-admin namespaces list <tenant-name>
----
+
*Output*:
+
[source,bash]
----
"<tenant-name>/default"
----

. Retrieve the topics within a namespace:
+
[source,bash]
----
./pulsar-admin topics list <tenant-name>/default
----
+
*Output*:
+
[source,bash]
----
"persistent://<tenant-name>/default/<topic-name>"
----

The URI, `persistent://<tenant-name>/default/<topic-name>`, is what we'll use to target a particular topic in the following sections.


For more information on `pulsar-admin` see the Apache Pulsar http://pulsar.apache.org/tools/pulsar-admin/2.7.0-SNAPSHOT[documentation]. 

[#produce-some-messages]
=== Produce some messages for your topic

Let's begin by sending some messages to your Astra Streaming instance using the `pulsar-client produce` command. You'll produce 100 `Hello world` messages:

[source,bash]
----
./pulsar-client produce -m "Hello world" -n 100 persistent://<tenant-name>/default/<topic-name>
----

*Output*:

[source,bash]
----
13:52:49.857 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0x8efe7ee3, L:/192.168.50.153:60842 - R:pulsar-aws-useast2.dev.streaming.datastax.com/3.130.180.131:6651]] Connected to server
... Additional status messages...
R:pulsar-aws-useast2.dev.streaming.datastax.com/3.130.180.131:6651] Disconnected
13:52:59.609 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 100 messages successfully produced
----

[#consume-some-messages]
=== Consume messages from your topic

With some messages in your topic, you can use `pulsar-client consume` to consume one of them:

[source,bash]
----
./pulsar-client consume -p Earliest -t Shared -s test-subscription persistent://<tenant-name>/default/<topic-name>
----

*Output*:

You'll see the content of the message following `----- got message -----`:

[source,bash]
----
13:56:16.612 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0x34f3b14e, L:/192.168.50.153:60858 - R:pulsar-aws-useast2.dev.streaming.datastax.com/3.130.180.131:6651]] Connected to server
... Additional status messages...
----- got message -----
key:[null], properties:[], content:Hello world
13:56:17.319 [main] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: pulsar+ssl://pulsar-aws-useast2.dev.streaming.datastax.com:6651
13:56:17.382 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConsumerImpl - [persistent://example-tenant/default/example-topic] [test-subscription] Closed consumer
13:56:17.388 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ClientCnx - [id: 0x34f3b14e, L:/192.168.50.153:60858 ! R:pulsar-aws-useast2.dev.streaming.datastax.com/3.130.180.131:6651] Disconnected
13:56:17.393 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ClientCnx - [id: 0x1339b07b, L:/192.168.50.153:60859 ! R:pulsar-aws-useast2.dev.streaming.datastax.com/3.130.180.131:6651] Disconnected
13:56:17.397 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 1 messages successfully consumed
----

Of course, you created 100 messages, and consumed one, so that means there are still 99 messages hanging around in the topic. We can specify the `-n 99` flag to consume the remaining messages:

[source,bash]
----
./pulsar-client consume -p Earliest -t Shared -n 99 -s test-subscription persistent://<tenant-name>/default/<topic-name>
----

*Output*:

You'll see the additional messages scroll by:

[source,bash]
----
14:18:09.990 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0xe2a6fe1f, L:/192.168.50.153:60958 - R:pulsar-aws-useast2.dev.streaming.datastax.com/3.143.105.197:6651]] Connected to server
... Additional status messages...
----- got message -----
key:[null], properties:[], content:hello world
----- got message -----
key:[null], properties:[], content:hello world
----- got message -----
key:[null], properties:[], content:hello world
... Additional retrieved messages...
14:18:10.760 [main] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: pulsar+ssl://pulsar-aws-useast2.dev.streaming.datastax.com:6651
14:18:10.809 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConsumerImpl - [persistent://example-tenant/default/example-topic] [test-subscription] Closed consumer
14:18:10.812 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ClientCnx - [id: 0x81b78021, L:/192.168.50.153:60959 ! R:pulsar-aws-useast2.dev.streaming.datastax.com/3.143.105.197:6651] Disconnected
14:18:10.817 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ClientCnx - [id: 0xe2a6fe1f, L:/192.168.50.153:60958 ! R:pulsar-aws-useast2.dev.streaming.datastax.com/3.143.105.197:6651] Disconnected
14:18:10.821 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 99 messages successfully consumed
----

For more information on `pulsar-client` see the Apache Pulsar https://pulsar.apache.org/docs/en/reference-cli-tools[documentation]

== Next 
